index:
    path: /
    controller: App\Controller\MainController:index

team:
    path: /equipe
    controller: App\Controller\EquipeController:index

team_details:
    path: /equipe/{id_equipe}/
    controller: App\Controller\EquipeController:equipeDetails

delete_from_project:
    path: /delete_from_project/{id_projet}/{id_consultant}
    controller: App\Controller\ProjetController:deleteFromProject