index:
    path: /
    controller: App\Controller\MainController:index

list_projet:
    path: /list
    controller: App\Controller\ProjetController:index

update_projet:
    path: /update/{id}
    controller: App\Controller\ProjetController:update

create_projet:
    path: /create/
    controller: App\Controller\ProjetController:index

delete_projet:
    path: /delete/{id}
    controller: App\Controller\ProjetController:delete
